#ddev-generated
# Simple template to demonstrate webhook-tester
services:
  webhook-tester:
    container_name: ddev-${DDEV_SITENAME}-webhook-tester
    image: ghcr.io/tarampampam/webhook-tester
    restart: "unless-stopped"
    networks: [default, ddev_default]
    # These labels ensure this service is discoverable by DDEV.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}

    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
    environment:
      VIRTUAL_HOST: "webhook-tester.$DDEV_HOSTNAME"
      HTTP_EXPOSE: "80:8080"
      AUTO_CREATE_SESSIONS: true
